package shopxedap.com.domain;

// Generated Nov 13, 2014 3:37:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtDonDatHang generated by hbm2java
 */
@Entity
@Table(name = "ct_don_dat_hang")
public class CtDonDatHang implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCTDDH", unique = true, nullable = false)
	private Integer idCtddh;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSP")
	private SanPham sanPham;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDDH")
	private DonDatHang donDatHang;

	@Column(name = "soLuongDatHang")
	private Integer soLuongDatHang;

	@Column(name = "donGia")
	private Integer donGia;

	@Column(name = "thanhTien", precision = 12, scale = 0)
	private Float thanhTien;

	public CtDonDatHang() {
	}

	public CtDonDatHang(SanPham sanPham, DonDatHang donDatHang,
			Integer soLuongDatHang, Integer donGia, Float thanhTien) {
		this.sanPham = sanPham;
		this.donDatHang = donDatHang;
		this.soLuongDatHang = soLuongDatHang;
		this.donGia = donGia;
		this.thanhTien = thanhTien;
	}

	public Integer getIdCtddh() {
		return this.idCtddh;
	}

	public void setIdCtddh(Integer idCtddh) {
		this.idCtddh = idCtddh;
	}

	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	public DonDatHang getDonDatHang() {
		return this.donDatHang;
	}

	public void setDonDatHang(DonDatHang donDatHang) {
		this.donDatHang = donDatHang;
	}

	public Integer getSoLuongDatHang() {
		return this.soLuongDatHang;
	}

	public void setSoLuongDatHang(Integer soLuongDatHang) {
		this.soLuongDatHang = soLuongDatHang;
	}

	public Integer getDonGia() {
		return this.donGia;
	}

	public void setDonGia(Integer donGia) {
		this.donGia = donGia;
	}

	public Float getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(Float thanhTien) {
		this.thanhTien = thanhTien;
	}

}
