package shopxedap.com.domain;

// Generated Nov 13, 2014 3:37:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtPhieuNhap generated by hbm2java
 */
@Entity
@Table(name = "ct_phieu_nhap")
public class CtPhieuNhap implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCTPN", unique = true, nullable = false)
	private Integer idCtpn;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSP")
	private SanPham sanPham;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPN")
	private PhieuNhap phieuNhap;

	@Column(name = "soLuongNhap")
	private Integer soLuongNhap;

	public CtPhieuNhap() {
	}

	public CtPhieuNhap(SanPham sanPham, PhieuNhap phieuNhap, Integer soLuongNhap) {
		this.sanPham = sanPham;
		this.phieuNhap = phieuNhap;
		this.soLuongNhap = soLuongNhap;
	}

	public Integer getIdCtpn() {
		return this.idCtpn;
	}

	public void setIdCtpn(Integer idCtpn) {
		this.idCtpn = idCtpn;
	}

	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	public PhieuNhap getPhieuNhap() {
		return this.phieuNhap;
	}

	public void setPhieuNhap(PhieuNhap phieuNhap) {
		this.phieuNhap = phieuNhap;
	}

	public Integer getSoLuongNhap() {
		return this.soLuongNhap;
	}

	public void setSoLuongNhap(Integer soLuongNhap) {
		this.soLuongNhap = soLuongNhap;
	}

}
