package shopxedap.com.domain;

// Generated Nov 13, 2014 3:37:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonDatHang generated by hbm2java
 */
@Entity
@Table(name = "don_dat_hang")
public class DonDatHang implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDDH", unique = true, nullable = false)
	private Integer idDdh;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTTDH")
	private TrangThaiDh trangThaiDh;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser")
	private NguoiDung nguoiDung;

	@Temporal(TemporalType.DATE)
	@Column(name = "tgDH", length = 10)
	private Date tgDh;

	@Column(name = "tongTien", precision = 12, scale = 0)
	private Float tongTien;

	@Column(name = "daThanhToan")
	private Boolean daThanhToan;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donDatHang")
	private Set<CtDonDatHang> ctDonDatHangs = new HashSet<CtDonDatHang>(0);

	public DonDatHang() {
	}

	public DonDatHang(TrangThaiDh trangThaiDh, NguoiDung nguoiDung, Date tgDh,
			Float tongTien, Boolean daThanhToan, Set<CtDonDatHang> ctDonDatHangs) {
		this.trangThaiDh = trangThaiDh;
		this.nguoiDung = nguoiDung;
		this.tgDh = tgDh;
		this.tongTien = tongTien;
		this.daThanhToan = daThanhToan;
		this.ctDonDatHangs = ctDonDatHangs;
	}

	public Integer getIdDdh() {
		return this.idDdh;
	}

	public void setIdDdh(Integer idDdh) {
		this.idDdh = idDdh;
	}

	public TrangThaiDh getTrangThaiDh() {
		return this.trangThaiDh;
	}

	public void setTrangThaiDh(TrangThaiDh trangThaiDh) {
		this.trangThaiDh = trangThaiDh;
	}

	public NguoiDung getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(NguoiDung nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	public Date getTgDh() {
		return this.tgDh;
	}

	public void setTgDh(Date tgDh) {
		this.tgDh = tgDh;
	}

	public Float getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(Float tongTien) {
		this.tongTien = tongTien;
	}

	public Boolean getDaThanhToan() {
		return this.daThanhToan;
	}

	public void setDaThanhToan(Boolean daThanhToan) {
		this.daThanhToan = daThanhToan;
	}

	public Set<CtDonDatHang> getCtDonDatHangs() {
		return this.ctDonDatHangs;
	}

	public void setCtDonDatHangs(Set<CtDonDatHang> ctDonDatHangs) {
		this.ctDonDatHangs = ctDonDatHangs;
	}

}
