package shopxedap.com.domain;

// Generated Nov 13, 2014 3:37:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NguoiDung generated by hbm2java
 */
@Entity
@Table(name = "nguoi_dung")
public class NguoiDung implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	private Integer idUser;

	@Column(name = "tenDangNhap", length = 50)
	private String tenDangNhap;

	@Column(name = "matKhau", length = 128)
	private String matKhau;

	@Column(name = "hoTen", length = 50)
	private String hoTen;

	@Column(name = "email", length = 50)
	private String email;

	@Column(name = "diaChi", length = 50)
	private String diaChi;

	@Column(name = "dienThoai")
	private Integer dienThoai;

	@Column(name = "laQuanTri")
	private Boolean laQuanTri;

	@Column(name = "soDuTK")
	private Integer soDuTk;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nguoiDung")
	private Set<DonDatHang> donDatHangs = new HashSet<DonDatHang>(0);

	public NguoiDung() {
	}

	public NguoiDung(String tenDangNhap, String matKhau, String hoTen,
			String email, String diaChi, Integer dienThoai, Boolean laQuanTri,
			Integer soDuTk, Set<DonDatHang> donDatHangs) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
		this.hoTen = hoTen;
		this.email = email;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.laQuanTri = laQuanTri;
		this.soDuTk = soDuTk;
		this.donDatHangs = donDatHangs;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public Integer getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(Integer dienThoai) {
		this.dienThoai = dienThoai;
	}

	public Boolean getLaQuanTri() {
		return this.laQuanTri;
	}

	public void setLaQuanTri(Boolean laQuanTri) {
		this.laQuanTri = laQuanTri;
	}

	public Integer getSoDuTk() {
		return this.soDuTk;
	}

	public void setSoDuTk(Integer soDuTk) {
		this.soDuTk = soDuTk;
	}

	public Set<DonDatHang> getDonDatHangs() {
		return this.donDatHangs;
	}

	public void setDonDatHangs(Set<DonDatHang> donDatHangs) {
		this.donDatHangs = donDatHangs;
	}

}
