package shopxedap.com.domain;

// Generated Nov 13, 2014 3:37:51 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "san_pham")
public class SanPham implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSP", unique = true, nullable = false)
	private Integer idSp;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLoaiSP")
	private LoaiSanPham loaiSanPham;

	@Column(name = "maSP", length = 5)
	private String maSp;

	@Column(name = "tenSP", length = 50)
	private String tenSp;

	@Column(name = "hinhSP", length = 128)
	private String hinhSp;

	@Column(name = "giaSP", precision = 12, scale = 0)
	private BigDecimal giaSp;

	@Column(name = "dacDiemSP", length = 250)
	private String dacDiemSp;

	@Temporal(TemporalType.DATE)
	@Column(name = "date_in", length = 10)
	private Date dateIn;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	private Set<CtPhieuNhap> ctPhieuNhaps = new HashSet<CtPhieuNhap>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	private Set<TonKho> tonKhos = new HashSet<TonKho>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	private Set<CtDonDatHang> ctDonDatHangs = new HashSet<CtDonDatHang>(0);

	public SanPham() {
	}

	public SanPham(LoaiSanPham loaiSanPham, String maSp, String tenSp,
			String hinhSp, BigDecimal giaSp, String dacDiemSp, Date dateIn,
			Set<CtPhieuNhap> ctPhieuNhaps, Set<TonKho> tonKhos,
			Set<CtDonDatHang> ctDonDatHangs) {
		this.loaiSanPham = loaiSanPham;
		this.maSp = maSp;
		this.tenSp = tenSp;
		this.hinhSp = hinhSp;
		this.giaSp = giaSp;
		this.dacDiemSp = dacDiemSp;
		this.dateIn = dateIn;
		this.ctPhieuNhaps = ctPhieuNhaps;
		this.tonKhos = tonKhos;
		this.ctDonDatHangs = ctDonDatHangs;
	}

	public Integer getIdSp() {
		return this.idSp;
	}

	public void setIdSp(Integer idSp) {
		this.idSp = idSp;
	}

	public LoaiSanPham getLoaiSanPham() {
		return this.loaiSanPham;
	}

	public void setLoaiSanPham(LoaiSanPham loaiSanPham) {
		this.loaiSanPham = loaiSanPham;
	}

	public String getMaSp() {
		return this.maSp;
	}

	public void setMaSp(String maSp) {
		this.maSp = maSp;
	}

	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	public String getHinhSp() {
		return this.hinhSp;
	}

	public void setHinhSp(String hinhSp) {
		this.hinhSp = hinhSp;
	}

	public BigDecimal getGiaSp() {
		return this.giaSp;
	}

	public void setGiaSp(BigDecimal giaSp) {
		this.giaSp = giaSp;
	}

	public String getDacDiemSp() {
		return this.dacDiemSp;
	}

	public void setDacDiemSp(String dacDiemSp) {
		this.dacDiemSp = dacDiemSp;
	}

	public Date getDateIn() {
		return this.dateIn;
	}

	public void setDateIn(Date dateIn) {
		this.dateIn = dateIn;
	}

	public Set<CtPhieuNhap> getCtPhieuNhaps() {
		return this.ctPhieuNhaps;
	}

	public void setCtPhieuNhaps(Set<CtPhieuNhap> ctPhieuNhaps) {
		this.ctPhieuNhaps = ctPhieuNhaps;
	}

	public Set<TonKho> getTonKhos() {
		return this.tonKhos;
	}

	public void setTonKhos(Set<TonKho> tonKhos) {
		this.tonKhos = tonKhos;
	}

	public Set<CtDonDatHang> getCtDonDatHangs() {
		return this.ctDonDatHangs;
	}

	public void setCtDonDatHangs(Set<CtDonDatHang> ctDonDatHangs) {
		this.ctDonDatHangs = ctDonDatHangs;
	}

}
